"""
SubSense LoRa SX126x Protocol, Driver & Framing Verification Suite
===================================================================
Validates:
1. Register configuration byte calculation matching loramain sx126x.py
2. Wire packet framing, fragmentation, and multi-chunk reassembly
3. Hardware RSSI byte decoding formula
4. Relay deduplication ring and hop-counter propagation
5. Gateway Bridge serial and direct-lora ingestion compatibility
"""

import json
import os
import struct
import sys
import time
import unittest
from unittest.mock import MagicMock, patch

# Add workspace paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, "gateway-bridge"))
sys.path.insert(0, os.path.join(BASE_DIR, "gateway-bridge", "drivers"))

from bridge import to_canonical, GatewayBridge, SerialJSONExtractor
from sx126x import sx126x


class TestLoraSx126xProtocol(unittest.TestCase):

    def test_lora_register_configuration_matching_loramain(self):
        """
        Verify that the register configuration bytes generated by the sx126x driver
        for 865 MHz, 22 dBm power, 2400 bps air speed, and RSSI enabled match
        the loramain hardware specification exactly.
        """
        # Mock serial to avoid opening actual COM port
        with patch("serial.Serial") as mock_serial_cls:
            mock_ser = MagicMock()
            mock_ser.in_waiting = 1
            mock_ser.read.return_value = bytes([0xC1, 0x00, 0x09])  # ACK
            mock_serial_cls.return_value = mock_ser

            driver = sx126x(
                serial_num="COM_TEST",
                freq=865,
                addr=0,
                power=22,
                rssi=True,
                air_speed=2400
            )

            cfg = driver.cfg_reg
            # 0: Command (0xC2)
            self.assertEqual(cfg[0], 0xC2)
            # 1: Start register (0x00)
            self.assertEqual(cfg[1], 0x00)
            # 2: Length (0x09 bytes)
            self.assertEqual(cfg[2], 0x09)
            # 3-4: Node address (0x0000)
            self.assertEqual(cfg[3], 0x00)
            self.assertEqual(cfg[4], 0x00)
            # 5: Net ID (0x00)
            self.assertEqual(cfg[5], 0x00)
            # 6: REG0 -> UART 9600 (0x60) + 2400 bps air speed (0x02) = 0x62
            self.assertEqual(cfg[6], 0x62)
            # 7: REG1 -> 240B packet (0x00) + 22dBm power (0x00) + noise RSSI (0x20) = 0x20
            self.assertEqual(cfg[7], 0x20)
            # 8: REG2 -> Channel offset for 865 MHz (865 - 850 = 15 = 0x0F)
            self.assertEqual(cfg[8], 15)
            # 9: REG3 -> Fixed mode (0x40) + WOR (0x03) + packet RSSI enable (0x80) = 0xC3
            self.assertEqual(cfg[9], 0xC3)
            # 10-11: Crypt (0x0000)
            self.assertEqual(cfg[10], 0x00)
            self.assertEqual(cfg[11], 0x00)

    def test_lora_rssi_conversion_formula(self):
        """
        Verify that the hardware RSSI byte formula -(256 - raw) correctly decodes
        SX126x / E22 raw RSSI byte into authentic dBm.
        """
        # Formula: -(256 - raw)
        def decode_rssi(raw_byte):
            return -(256 - raw_byte)

        self.assertEqual(decode_rssi(192), -64)   # Typical strong mine tunnel signal
        self.assertEqual(decode_rssi(211), -45)   # Close proximity / bench test (1m)
        self.assertEqual(decode_rssi(156), -100)  # Near receiver sensitivity edge (-100 dBm)
        self.assertEqual(decode_rssi(136), -120)  # Deep attenuation threshold (-120 dBm)

    def test_lora_fixed_mode_packet_header(self):
        """
        Verify that send() formats packet with fixed-transmission header:
        [ADDR_HIGH, ADDR_LOW, CHANNEL] + PAYLOAD
        """
        with patch("serial.Serial") as mock_serial_cls:
            mock_ser = MagicMock()
            mock_ser.in_waiting = 0
            mock_serial_cls.return_value = mock_ser

            driver = sx126x("COM_TEST", freq=865, addr=0, power=22, rssi=True)

            mock_ser.write.reset_mock()
            driver.send("HELLO_LORA", target_addr=0xFFFF, channel=15)

            # Check written bytes
            written = mock_ser.write.call_args[0][0]
            # Fixed header: 0xFF, 0xFF, 15
            self.assertEqual(written[:3], bytes([0xFF, 0xFF, 15]))
            # Payload: "HELLO_LORA"
            self.assertEqual(written[3:], b"HELLO_LORA")

    def test_packet_fragmentation_and_reassembly(self):
        """
        Simulate LoRa multi-hop fragmentation and reassembly for a 350-byte JSON telemetry payload.
        Chunk size: 190 bytes payload + 15 bytes header = 205 bytes wire packet.
        """
        payload = json.dumps({
            "node_id": "SS-PANEL7-N042",
            "site_id": "PANEL7-JHARIA",
            "tenant_id": "tenant-jharia-01",
            "tilt_current": 1.42,
            "vibration_rms": 0.28,
            "battery_percent": 94,
            "rssi_dbm": -68,
            "hop_count": 1,
            "siren_triggered": False,
            "timestamp": "2026-09-11T12:00:00Z",
            "details": "Underground strata borehole monitoring panel 7 west face"
        })
        payload_bytes = payload.encode("utf-8")
        total_len = len(payload_bytes)
        self.assertGreater(total_len, 190)

        chunk_size = 190
        total_chunks = (total_len + chunk_size - 1) // chunk_size
        self.assertEqual(total_chunks, 2)

        # Build fragments (simulating subsense_lora_mesh_send)
        MAGIC = 0xA5
        msg_id = 42
        origin_mac = bytes([0x24, 0x6F, 0x28, 0x1A, 0xBC, 0x01])
        fragments = []

        for i in range(total_chunks):
            offset = i * chunk_size
            chunk_data = payload_bytes[offset:offset + chunk_size]
            chunk_len = len(chunk_data)

            # Header: magic(1), msg_id(1), chunk_idx(1), total_chunks(1), total_len(2), chunk_len(2), hop(1), mac(6)
            header = struct.pack("<BBBBHHB6s", MAGIC, msg_id, i, total_chunks, total_len, chunk_len, 0, origin_mac)
            self.assertEqual(len(header), 15)
            fragments.append(header + chunk_data)

        # Reassemble fragments (simulating gateway handle_gateway_packet)
        reassembled_buf = bytearray(total_len)
        chunks_received = 0

        for frag in fragments:
            hdr = frag[:15]
            magic, m_id, idx, n_chunks, t_len, c_len, hop, mac = struct.unpack("<BBBBHHB6s", hdr)
            self.assertEqual(magic, MAGIC)
            self.assertEqual(m_id, msg_id)

            data = frag[15:15 + c_len]
            reassembled_buf[idx * chunk_size:idx * chunk_size + c_len] = data
            chunks_received += 1

        self.assertEqual(chunks_received, total_chunks)
        decoded_json = reassembled_buf.decode("utf-8")
        parsed = json.loads(decoded_json)
        self.assertEqual(parsed["node_id"], "SS-PANEL7-N042")
        self.assertEqual(parsed["tilt_current"], 1.42)

    def test_relay_deduplication_and_hop_increment(self):
        """
        Verify that relay deduplication correctly drops duplicate packets and
        increments the hop counter for novel packets.
        """
        MAGIC = 0xA5
        origin_mac = bytes([0x24, 0x6F, 0x28, 0x1A, 0xBC, 0x01])

        # Dedup ring buffer simulation
        dedup_cache = {}
        MAX_HOPS = 3

        def simulate_relay_receive(msg_id, chunk_idx, hop_count):
            if hop_count >= MAX_HOPS:
                return False, "DROP_MAX_HOPS"

            key = (origin_mac, msg_id, chunk_idx)
            if key in dedup_cache:
                return False, "DROP_DUPLICATE"

            dedup_cache[key] = time.time()
            new_hop = hop_count + 1
            return True, new_hop

        # 1. First reception: novel packet -> forward with hop increment
        fwd_ok, hop = simulate_relay_receive(msg_id=1, chunk_idx=0, hop_count=0)
        self.assertTrue(fwd_ok)
        self.assertEqual(hop, 1)

        # 2. Duplicate reception of same fragment -> drop
        dup_ok, reason = simulate_relay_receive(msg_id=1, chunk_idx=0, hop_count=0)
        self.assertFalse(dup_ok)
        self.assertEqual(reason, "DROP_DUPLICATE")

        # 3. Novel fragment of same message -> forward
        fwd2_ok, hop2 = simulate_relay_receive(msg_id=1, chunk_idx=1, hop_count=0)
        self.assertTrue(fwd2_ok)
        self.assertEqual(hop2, 1)

        # 4. Hop count limit test (hop >= 3) -> drop
        fwd3_ok, reason3 = simulate_relay_receive(msg_id=2, chunk_idx=0, hop_count=3)
        self.assertFalse(fwd3_ok)
        self.assertEqual(reason3, "DROP_MAX_HOPS")

    def test_gateway_bridge_canonical_mapping_with_lora_rssi(self):
        """
        Verify that raw LoRa Gateway telemetry with physical RSSI and hop count
        adapts accurately into the Canonical SensorReading contract without data fabrication.
        """
        raw_lora_telemetry = {
            "node_id": "SS-PANEL7-N042",
            "site_id": "PANEL7-JHARIA",
            "tenant_id": "tenant-jharia-01",
            "zone_id": "PANEL-7-WEST",
            "tilt_current": 3.85,
            "vibration_rms": 0.42,
            "battery_percent": 89,
            "rssi_dbm": -68,
            "hop_count": 1,
            "siren_triggered": False,
            "timestamp": "2026-09-11T12:30:00Z"
        }

        canonical = to_canonical(raw_lora_telemetry)

        # Validated fields
        self.assertEqual(canonical["node_id"], "SS-PANEL7-N042")
        self.assertEqual(canonical["site_id"], "PANEL7-JHARIA")
        self.assertEqual(canonical["readings"]["tilt_deg"], 3.85)
        self.assertEqual(canonical["readings"]["vibration_rms_mm_s"], 0.42)
        self.assertEqual(canonical["node_health"]["rssi_dbm"], -68)
        self.assertEqual(canonical["node_health"]["hop_count"], 1)

        # Strict Zero-Fabrication invariant
        self.assertIsNone(canonical["readings"]["displacement_mm"])
        self.assertIsNone(canonical["readings"]["crack_index"])
        self.assertFalse(canonical["sensor_availability"]["displacement"])
        self.assertFalse(canonical["sensor_availability"]["crack"])


    def test_compact_lora_packet_to_canonical_mapping(self):
        """
        Verify that ultra-compact high-speed LoRa packets (<130B) expand accurately
        into the Canonical SubSense SensorReading contract.
        """
        compact_pkt = {
            "node": "SS-PANEL7-N042",
            "tilt": 61.77,
            "vib": 2.45,
            "bat": 94,
            "siren": True,
            "score": 0.95,
            "seq": 21,
            "ts": "2026-09-11T12:30:00Z"
        }

        canonical = to_canonical(compact_pkt)

        self.assertEqual(canonical["node_id"], "SS-PANEL7-N042")
        self.assertEqual(canonical["readings"]["tilt_deg"], 61.77)
        self.assertEqual(canonical["readings"]["vibration_rms_mm_s"], 2.45)
        self.assertTrue(canonical["siren_triggered"])
        self.assertEqual(canonical["anomaly_score"], 0.95)
        self.assertEqual(canonical["node_health"]["battery_percent"], 94)
        self.assertIsNone(canonical["readings"]["displacement_mm"])
        self.assertIsNone(canonical["readings"]["crack_index"])
        self.assertFalse(canonical["sensor_availability"]["displacement"])
        self.assertFalse(canonical["sensor_availability"]["crack"])

    def test_lora_payload_within_240_byte_hardware_mtu(self):
        """
        Verify that generated LoRa telemetry packets are strictly < 240 bytes
        to prevent hardware packet splitting, radio collisions, and corrupted fragments.
        """
        from edge.lora_nodes.sensor_node import LoRaSensorNode

        with patch("serial.Serial"):
            node = LoRaSensorNode(node_id="SS-PANEL7-N042", port="COM_MOCK")
            # Build packet with maximum float length
            payload_str = node.build_telemetry_packet(61.77123, 14.89123, True)
            self.assertLess(len(payload_str.encode("utf-8")), 240)
            data = json.loads(payload_str)
            self.assertEqual(data["node_id"], "SS-PANEL7-N042")
            self.assertEqual(data["tilt_current"], 61.771)
            self.assertEqual(data["vibration_rms"], 14.891)
            self.assertTrue(data["siren_triggered"])

    def test_gateway_backwards_stream_json_extraction(self):
        """
        Verify that gateway backwards-scanning stream parser successfully recovers valid JSON
        even when preceded by noise or partial packet fragments.
        """
        from edge.lora_nodes.gateway_node import LoRaGatewayNode

        with patch("serial.Serial"):
            gw = LoRaGatewayNode(port="COM_MOCK")
            processed = []
            gw.process_incoming_packet = lambda d, r: processed.append(d)

            # 1. Noise fragment followed by complete JSON
            noise_and_json = 'corrupted_fragment{"node":"SS-01","tilt":27.5,"vib":0.0}'
            gw.handle_incoming_chunk(noise_and_json, rssi=-58)
            self.assertEqual(len(processed), 1)
            self.assertEqual(processed[0]["tilt"], 27.5)

            # 2. Chunked JSON split across two calls
            gw.handle_incoming_chunk('{"node":"SS-02",', rssi=-60)
            self.assertEqual(len(processed), 1)  # Still 1, waiting for closing
            gw.handle_incoming_chunk('"tilt":61.8,"vib":0.1}', rssi=-60)
            self.assertEqual(len(processed), 2)  # Now 2
            self.assertEqual(processed[1]["node"], "SS-02")
            self.assertEqual(processed[1]["tilt"], 61.8)


if __name__ == "__main__":
    unittest.main()
